import {
    Document, Packer, Paragraph, Table, TableRow, TableCell,
    TextRun, AlignmentType, BorderStyle, HeadingLevel,
    WidthType, ShadingType, Header, Footer, PageNumber,
    NumberFormat
} from 'docx'
import { saveAs } from 'file-saver'

// ═══════════════════════════════════════════════════════════════════
// VIRUDTI JEWELLS — Luxury Word Export Engine
// ═══════════════════════════════════════════════════════════════════

const GOLD_HEX = 'D4AF37'
const DARK_BG = '1A1A1A'
const WHITE = 'FFFFFF'
const MUTED = '888888'
const BORDER_COLOR = '333333'

// ─── Shared Styles ────────────────────────────────────────────────
const thinBorder = { style: BorderStyle.SINGLE, size: 1, color: BORDER_COLOR }
const noBorder = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' }

function brandHeader(): Header {
    return new Header({
        children: [
            new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                    new TextRun({ text: 'VIRUDTI JEWELLS', bold: true, size: 16, color: GOLD_HEX, font: 'Segoe UI' }),
                    new TextRun({ text: '  |  Jewelry ERP System', size: 14, color: MUTED, font: 'Segoe UI' }),
                ],
            }),
        ],
    })
}

function brandFooter(): Footer {
    return new Footer({
        children: [
            new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                    new TextRun({ text: 'Confidential  ·  Generated by Virudti Jewells ERP  ·  Page ', size: 14, color: MUTED, font: 'Segoe UI' }),
                    new TextRun({ children: [PageNumber.CURRENT], size: 14, color: MUTED, font: 'Segoe UI' }),
                ],
            }),
        ],
    })
}

function titleBlock(title: string, subtitle?: string): Paragraph[] {
    return [
        new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 100 },
            children: [
                new TextRun({ text: '◆', size: 32, color: GOLD_HEX, font: 'Segoe UI' }),
            ],
        }),
        new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 60 },
            children: [
                new TextRun({ text: 'VIRUDTI JEWELLS', bold: true, size: 36, color: GOLD_HEX, font: 'Segoe UI' }),
            ],
        }),
        new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
            children: [
                new TextRun({ text: 'Timeless Gold, Trusted Purity', italics: true, size: 18, color: MUTED, font: 'Segoe UI' }),
            ],
        }),
        new Paragraph({
            alignment: AlignmentType.CENTER,
            heading: HeadingLevel.HEADING_1,
            spacing: { after: 80 },
            children: [
                new TextRun({ text: title, bold: true, size: 32, color: DARK_BG, font: 'Segoe UI' }),
            ],
        }),
        ...(subtitle ? [new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 60 },
            children: [new TextRun({ text: subtitle, size: 18, color: MUTED, font: 'Segoe UI' })],
        })] : []),
        new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 300 },
            children: [
                new TextRun({ text: `Generated: ${new Date().toLocaleString('en-IN', { dateStyle: 'long', timeStyle: 'short' })}`, size: 16, color: MUTED, font: 'Segoe UI' }),
            ],
        }),
        // Divider
        new Paragraph({
            spacing: { after: 200 },
            border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: GOLD_HEX } },
            children: [],
        }),
    ]
}

function summaryCard(label: string, value: string): TableCell {
    return new TableCell({
        width: { size: 25, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.SOLID, color: 'F9F6EE' },
        borders: {
            top: thinBorder, bottom: thinBorder,
            left: thinBorder, right: thinBorder,
        },
        children: [
            new Paragraph({
                spacing: { before: 80, after: 20 },
                alignment: AlignmentType.CENTER,
                children: [new TextRun({ text: label, size: 14, color: MUTED, font: 'Segoe UI', allCaps: true })],
            }),
            new Paragraph({
                spacing: { after: 80 },
                alignment: AlignmentType.CENTER,
                children: [new TextRun({ text: value, bold: true, size: 24, color: DARK_BG, font: 'Segoe UI' })],
            }),
        ],
    })
}

function summaryRow(metrics: { label: string; value: string }[]): Table {
    return new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
            new TableRow({
                children: metrics.map(m => summaryCard(m.label, m.value)),
            }),
        ],
    })
}

function sectionHeading(text: string): Paragraph {
    return new Paragraph({
        spacing: { before: 300, after: 150 },
        children: [
            new TextRun({ text: '━━  ', color: GOLD_HEX, size: 16, font: 'Segoe UI' }),
            new TextRun({ text: text, bold: true, size: 22, color: DARK_BG, font: 'Segoe UI' }),
        ],
    })
}

function dataTable(columns: string[], rows: string[][]): Table {
    const headerRow = new TableRow({
        tableHeader: true,
        children: columns.map(col => new TableCell({
            shading: { type: ShadingType.SOLID, color: DARK_BG },
            borders: { top: thinBorder, bottom: thinBorder, left: thinBorder, right: thinBorder },
            children: [
                new Paragraph({
                    alignment: AlignmentType.LEFT,
                    spacing: { before: 60, after: 60 },
                    children: [new TextRun({ text: col, bold: true, size: 16, color: GOLD_HEX, font: 'Segoe UI', allCaps: true })],
                }),
            ],
        })),
    })

    const dataRows = rows.map((row, rowIdx) =>
        new TableRow({
            children: row.map(cell => new TableCell({
                shading: rowIdx % 2 === 0
                    ? { type: ShadingType.SOLID, color: WHITE }
                    : { type: ShadingType.SOLID, color: 'FAFAFA' },
                borders: { top: thinBorder, bottom: thinBorder, left: thinBorder, right: thinBorder },
                children: [
                    new Paragraph({
                        spacing: { before: 40, after: 40 },
                        children: [new TextRun({ text: cell || '—', size: 16, color: DARK_BG, font: 'Segoe UI' })],
                    }),
                ],
            })),
        })
    )

    return new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [headerRow, ...dataRows],
    })
}

// ═══════════════════════════════════════════════════════════════════
// EXPORT FUNCTIONS
// ═══════════════════════════════════════════════════════════════════

export async function exportSalesReport(reportData: any) {
    const { sales, totalRevenue, totalSales, totalItems, byPayment } = reportData

    const paymentSummary = Object.entries(byPayment)
        .map(([method, amt]: [string, any]) => `${method}: ₹${amt.toLocaleString()}`)
        .join('  |  ')

    const doc = new Document({
        sections: [{
            properties: {
                page: {
                    margin: { top: 720, right: 720, bottom: 720, left: 720 },
                    pageNumbers: { start: 1 },
                },
            },
            headers: { default: brandHeader() },
            footers: { default: brandFooter() },
            children: [
                ...titleBlock('Sales Report', 'Revenue & Transaction Analysis'),
                summaryRow([
                    { label: 'Total Revenue', value: `₹${totalRevenue.toLocaleString()}` },
                    { label: 'Transactions', value: String(totalSales) },
                    { label: 'Items Sold', value: String(totalItems) },
                    { label: 'Payment Split', value: paymentSummary.length > 30 ? `${Object.keys(byPayment).length} methods` : paymentSummary },
                ]),
                sectionHeading('Transaction Details'),
                dataTable(
                    ['Date', 'Customer', 'Items', 'Payment', 'Discount', 'Total'],
                    sales.map((s: any) => [
                        new Date(s.created_at).toLocaleDateString('en-IN'),
                        s.customer_name || 'Walk-in',
                        String(s.sale_items?.length ?? 0),
                        s.payment_method,
                        `₹${Number(s.discount_amount ?? 0).toLocaleString()}`,
                        `₹${Number(s.total_amount).toLocaleString()}`,
                    ])
                ),
            ],
        }],
    })

    const blob = await Packer.toBlob(doc)
    saveAs(blob, `Virudti_Sales_Report_${new Date().toISOString().slice(0, 10)}.docx`)
}

export async function exportStockReport(reportData: any) {
    const { items, totalStock, totalValue, lowStockCount, outOfStockCount } = reportData

    const doc = new Document({
        sections: [{
            properties: {
                page: {
                    margin: { top: 720, right: 720, bottom: 720, left: 720 },
                    pageNumbers: { start: 1 },
                },
            },
            headers: { default: brandHeader() },
            footers: { default: brandFooter() },
            children: [
                ...titleBlock('Stock Report', 'Inventory Levels & Valuation'),
                summaryRow([
                    { label: 'Total Units', value: totalStock.toLocaleString() },
                    { label: 'Total Value', value: `₹${totalValue.toLocaleString()}` },
                    { label: 'Low Stock', value: String(lowStockCount) },
                    { label: 'Out of Stock', value: String(outOfStockCount) },
                ]),
                sectionHeading('Inventory Breakdown'),
                dataTable(
                    ['Product', 'Branch', 'SKU', 'Stock', 'Price', 'Value'],
                    items.map((i: any) => [
                        i.product?.name ?? '—',
                        i.branch?.name ?? '—',
                        i.sku ?? '—',
                        String(i.stock_count),
                        `₹${Number(i.selling_price ?? 0).toLocaleString()}`,
                        `₹${(i.stock_count * Number(i.selling_price ?? 0)).toLocaleString()}`,
                    ])
                ),
            ],
        }],
    })

    const blob = await Packer.toBlob(doc)
    saveAs(blob, `Virudti_Stock_Report_${new Date().toISOString().slice(0, 10)}.docx`)
}

export async function exportTrendsReport(reportData: any) {
    const { entries, totalMovements, adds, removes } = reportData

    const doc = new Document({
        sections: [{
            properties: {
                page: {
                    margin: { top: 720, right: 720, bottom: 720, left: 720 },
                    pageNumbers: { start: 1 },
                },
            },
            headers: { default: brandHeader() },
            footers: { default: brandFooter() },
            children: [
                ...titleBlock('Trend Analysis', 'Stock Movements Over Time'),
                summaryRow([
                    { label: 'Total Movements', value: String(totalMovements) },
                    { label: 'Stock Added', value: String(adds) },
                    { label: 'Stock Removed', value: String(removes) },
                    { label: 'Net Change', value: String(adds - removes) },
                ]),
                sectionHeading('Movement History'),
                dataTable(
                    ['Date', 'Product', 'Action', 'Previous', 'New', 'Reason'],
                    entries.map((e: any) => [
                        new Date(e.created_at).toLocaleDateString('en-IN'),
                        e.product?.name ?? '—',
                        e.action_type,
                        String(e.old_count),
                        String(e.new_count),
                        e.reason ?? '—',
                    ])
                ),
            ],
        }],
    })

    const blob = await Packer.toBlob(doc)
    saveAs(blob, `Virudti_Trend_Analysis_${new Date().toISOString().slice(0, 10)}.docx`)
}
